"""
make_fonts.py — one-off, run locally (NOT in CI). regenerates scripts/fonts.py.

subsets the OFL display + mono faces down to printable ascii plus a few
typographic marks, then stores them as base64 woff2 so every svg can embed
its own fonts and CI stays stdlib-only.

  pip install fonttools brotli
  python scripts/tools/make_fonts.py <InstrumentSerif-Regular.ttf> \
      <InstrumentSerif-Italic.ttf> <JetBrainsMono[wght].ttf>
"""

import base64
import io
import os
import sys

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

TEXT = "".join(chr(c) for c in range(0x20, 0x7F)) + "·—–’‘“”…•●×"


def woff2_b64(font):
    opts = subset.Options()
    opts.flavor = "woff2"
    opts.layout_features = ["kern", "liga"]
    opts.name_IDs = []
    opts.notdef_outline = True
    sub = subset.Subsetter(opts)
    sub.populate(text=TEXT)
    sub.subset(font)
    buf = io.BytesIO()
    font.flavor = "woff2"
    font.save(buf)
    return base64.b64encode(buf.getvalue()).decode("ascii")


def main(serif, serif_it, mono):
    out = {
        "SERIF_REGULAR": woff2_b64(TTFont(serif)),
        "SERIF_ITALIC": woff2_b64(TTFont(serif_it)),
    }
    for w in (400, 700):
        out[f"MONO_{w}"] = woff2_b64(
            instancer.instantiateVariableFont(TTFont(mono), {"wght": w}))

    dst = os.path.join(os.path.dirname(__file__), "..", "fonts.py")
    with open(dst, "w", encoding="utf-8") as f:
        f.write('"""generated by scripts/tools/make_fonts.py — do not edit.\n'
                'Instrument Serif and JetBrains Mono, SIL Open Font License 1.1."""\n\n')
        for k, v in out.items():
            f.write(f'{k} = "{v}"\n')
    print({k: len(v) for k, v in out.items()})


if __name__ == "__main__":
    main(*sys.argv[1:4])
