"""
make_posters.py — one-off, run locally (NOT in CI). regenerates
scripts/poster_images.py.

the engraved project posters, reduced to light line-work on black, cropped to
the card's right half, and floyd-steinberg dithered to 1 bit at display size —
the grainrad look. stored as base64 png so the cards can embed them.

  pip install pillow
  python scripts/tools/make_posters.py
"""

import base64
import io
import os

from PIL import Image, ImageOps

HERE = os.path.dirname(__file__)
SRC = os.path.join(HERE, "source")
DST = os.path.join(HERE, "..", "poster_images.py")
OUT_W, OUT_H = 430, 220

# project id -> dict:
#   file, mode   how to isolate the line-work from its ground
#   cy           crop centre, 0..1 of the source height
#   fit          letterbox the whole subject instead of cropping into it
#   zoom         with fit, how much of the frame the subject fills
#   floor        tones below this go black, so the ground stays clean
#   gain         scales what is left; below 1 it keeps the brights in the
#                mid-range, where dithering turns them into texture rather
#                than a solid white mass
#   gamma        bends the mid-tones; higher keeps the shadows sparse
POSTERS = {
    "lotusmcp": dict(file="poster-lotus2.jpg", mode="light", cy=0.42,
                     fit=True, zoom=2.05, floor=70, gain=0.56, gamma=1.4),
    "bugbouncer": dict(file="poster-beetle.jpg", mode="light", cy=0.50,
                       fit=True, zoom=1.3, floor=60, gain=0.62, gamma=1.3),
    "lily": dict(file="poster-lily.jpg", mode="dark", cy=0.50,
                 floor=70, gain=1.0, gamma=1.6),
}


def floor_cut(img, floor):
    """drop the faint tones (paper grain, haze) and rescale what is left."""
    return img.point(lambda x: 0 if x < floor
                     else round((x - floor) * 255 / (255 - floor)))


def isolate(img, mode, floor):
    if mode == "light":
        return floor_cut(ImageOps.grayscale(img), floor)
    if mode == "dark":
        # paper grain turns into speckle once inverted
        return floor_cut(ImageOps.invert(ImageOps.grayscale(img)), floor)
    # keep bright, unsaturated pixels (white marks on a coloured ground)
    hsv = img.convert("HSV")
    _, s, v = hsv.split()
    return _white(s, v)


def _white(s, v):
    sat, val = s.load(), v.load()
    out = Image.new("L", s.size)
    px = out.load()
    for y in range(s.size[1]):
        for x in range(s.size[0]):
            px[x, y] = max(0, val[x, y] - sat[x, y] * 2) if sat[x, y] < 110 else 0
    return out


def crop(img, cy, fit=False, zoom=1.0):
    if fit:
        # letterbox: keep the whole subject, black to the sides. the window is
        # centred on cy, so zooming in doesn't cut the top of the subject off.
        h = round(img.height / zoom)
        w = round(h * OUT_W / OUT_H)
        out = Image.new("L", (w, h))
        out.paste(img, ((w - img.width) // 2, round(h / 2 - cy * img.height)))
        return out
    w = img.width
    h = round(w * OUT_H / OUT_W)
    top = round(min(max(cy * img.height - h / 2, 0), img.height - h))
    return img.crop((0, top, w, top + h))


def bake(file, mode, cy, floor, gain, gamma, fit=False, zoom=1.0):
    img = Image.open(os.path.join(SRC, file)).convert("RGB")
    g = crop(isolate(img, mode, floor), cy, fit, zoom).resize((OUT_W, OUT_H), Image.LANCZOS)
    g = ImageOps.autocontrast(g, cutoff=1)
    g = g.point(lambda x: min(255, round(255 * gain * (x / 255) ** gamma)))
    bw = g.convert("1")                                   # floyd-steinberg
    ink = bw.histogram()[-1] / (OUT_W * OUT_H)
    buf = io.BytesIO()
    bw.save(buf, "PNG", optimize=True)
    return base64.b64encode(buf.getvalue()).decode("ascii"), ink


def main():
    lines = ['"""generated by scripts/tools/make_posters.py — do not edit."""', "",
             "POSTERS = {"]
    for pid, spec in POSTERS.items():
        b64, ink = bake(**spec)
        print(f"{pid}: {len(b64)} b64 chars, {ink:.1%} ink")
        lines.append(f'    "{pid}": ({OUT_W}, {OUT_H}, "{b64}"),')
    lines.append("}")
    with open(DST, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
