"""
make_posters.py — one-off, run locally (NOT in CI). regenerates
scripts/poster_images.py.

the engraved project posters, reduced to light line-work on black, cropped to
the card's right half, and floyd-steinberg dithered to 1 bit at display size —
the grainrad look. stored as base64 png so the cards can embed them.

  pip install pillow
  python scripts/tools/make_posters.py
"""

import base64
import io
import os

from PIL import Image, ImageOps

HERE = os.path.dirname(__file__)
SRC = os.path.join(HERE, "source")
DST = os.path.join(HERE, "..", "poster_images.py")
OUT_W, OUT_H = 430, 220

# project id -> (file, how to isolate the line-work, crop centre y as 0..1)
POSTERS = {
    "lotusmcp": ("poster-lotus.jpg", "light", 0.55),
    "bugbouncer": ("poster-signal.jpg", "white_on_colour", 0.69),
    "lily": ("poster-lily.jpg", "dark", 0.50),
}


def isolate(img, mode):
    if mode == "light":
        return ImageOps.grayscale(img)
    if mode == "dark":
        # paper grain turns into speckle once inverted; drop the faint tones
        inv = ImageOps.invert(ImageOps.grayscale(img))
        return inv.point(lambda x: 0 if x < 70 else round((x - 70) * 255 / 185))
    # keep bright, unsaturated pixels (white marks on a coloured ground)
    hsv = img.convert("HSV")
    _, s, v = hsv.split()
    return _white(s, v)


def _white(s, v):
    sat, val = s.load(), v.load()
    out = Image.new("L", s.size)
    px = out.load()
    for y in range(s.size[1]):
        for x in range(s.size[0]):
            px[x, y] = max(0, val[x, y] - sat[x, y] * 2) if sat[x, y] < 110 else 0
    return out


def crop(img, cy):
    w = img.width
    h = round(w * OUT_H / OUT_W)
    top = round(min(max(cy * img.height - h / 2, 0), img.height - h))
    return img.crop((0, top, w, top + h))


def bake(fname, mode, cy):
    img = Image.open(os.path.join(SRC, fname)).convert("RGB")
    g = crop(isolate(img, mode), cy).resize((OUT_W, OUT_H), Image.LANCZOS)
    g = ImageOps.autocontrast(g, cutoff=1)
    g = g.point(lambda x: int(255 * (x / 255) ** 1.6))   # keep shadows sparse
    bw = g.convert("1")                                   # floyd-steinberg
    buf = io.BytesIO()
    bw.save(buf, "PNG", optimize=True)
    return base64.b64encode(buf.getvalue()).decode("ascii")


def main():
    lines = ['"""generated by scripts/tools/make_posters.py — do not edit."""', "",
             "POSTERS = {"]
    for pid, (fname, mode, cy) in POSTERS.items():
        b64 = bake(fname, mode, cy)
        print(f"{pid}: {len(b64)} b64 chars")
        lines.append(f'    "{pid}": ({OUT_W}, {OUT_H}, "{b64}"),')
    lines.append("}")
    with open(DST, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
