"""
make_ace.py — one-off, run locally (NOT in CI). regenerates scripts/ace_image.py.

crops the crumpled ace of spades out of its black backdrop, lifts it slightly
(the source is very dark) without losing its mood, and stores it as base64 jpeg so gen_ace.py can embed
it — an <img> svg can't load external files.

  pip install pillow
  python scripts/tools/make_ace.py
"""

import base64
import io
import os

from PIL import Image, ImageEnhance, ImageOps

HERE = os.path.dirname(__file__)
SRC = os.path.join(HERE, "source", "ace.png")
DST = os.path.join(HERE, "..", "ace_image.py")
WIDTH = 450          # 1.5x the ~300px it is shown at
PAD = 12


def main():
    img = Image.open(SRC).convert("L")
    box = img.point(lambda v: 255 if v > 35 else 0).getbbox()
    l, t, r, b = box
    img = img.crop((max(0, l - PAD), max(0, t - PAD),
                    min(img.width, r + PAD), min(img.height, b + PAD)))
    img = ImageOps.autocontrast(img, cutoff=0.5)
    img = ImageEnhance.Brightness(img).enhance(0.8)
    h = round(img.height * WIDTH / img.width)
    img = img.resize((WIDTH, h), Image.LANCZOS)

    buf = io.BytesIO()
    img.save(buf, "JPEG", quality=60, optimize=True, progressive=True)
    b64 = base64.b64encode(buf.getvalue()).decode("ascii")
    with open(DST, "w", encoding="utf-8") as f:
        f.write('"""generated by scripts/tools/make_ace.py — do not edit."""\n\n')
        f.write(f"W, H = {WIDTH}, {h}\n")
        f.write(f'ACE_JPEG_B64 = "{b64}"\n')
    print(f"crop {box} -> {WIDTH}x{h}, {len(b64)} b64 chars")


if __name__ == "__main__":
    main()
