"""
hero.svg — the animated terminal hero.

a shell session boots, resolves identity line by line, and lands on the name.
animation is pure inline SMIL (per-line opacity reveal with begin-offsets, a
one-shot scan beam, a blinking cursor) so it renders consistently wherever the
other panels do. no external fonts, no js, no foreignObject.

regenerated by the pipeline so the live numbers (bugbouncer stars) stay current.
"""

from lib import (BG, PANEL, BORDER, GREEN, GREEN_DIM, CYAN, WHITE, GREY,
                 RED, AMBER, LIME, MONO, esc, write_svg, collect)

W, H = 860, 368
X = 30                 # left margin for text
Y0 = 88                # first body line baseline
LH = 30                # line height


def line(y, delay, segs, size=17, weight=500):
    """one reveal-on-load text line built from coloured tspans."""
    tspans = "".join(
        f'<tspan fill="{c}"{f" font-weight=\"{w}\"" if w else ""}>{esc(t)}</tspan>'
        for (t, c, w) in segs
    )
    return (f'<g opacity="0">'
            f'<animate attributeName="opacity" values="0;1" dur="0.45s" '
            f'begin="{delay}s" fill="freeze"/>'
            f'<text x="{X}" y="{y}" font-size="{size}" font-weight="{weight}" '
            f'font-family="{MONO}">{tspans}</text></g>')


def build():
    d = collect()
    bb = d["bugbouncer_stars"]

    body = []
    body.append(line(Y0 + 0 * LH, 0.15, [
        ("knight@kali", GREEN, 700), (":", GREY, 0), ("~", CYAN, 0),
        ("$ ", GREY, 0), ("./whoami --proof", WHITE, 0)]))
    body.append(line(Y0 + 1 * LH, 0.55, [
        ("[*] ", GREY, 0), ("resolving identity ", WHITE, 0),
        ("··········· ", GREY, 0),
        ("ok", GREEN, 700)]))
    body.append(line(Y0 + 2 * LH, 0.95, [
        ("role  ", GREEN, 0), (" : ", GREY, 0),
        ("security · systems · full-stack", WHITE, 0)]))
    body.append(line(Y0 + 3 * LH, 1.35, [
        ("mode  ", GREEN, 0), (" : ", GREY, 0),
        ("builds things, then breaks them", WHITE, 0)]))
    body.append(line(Y0 + 4 * LH, 1.75, [
        ("proof ", GREEN, 0), (" : ", GREY, 0),
        ("bugbouncer ", WHITE, 0), (f"{bb}★", CYAN, 700),
        ("  ·  ", GREY, 0), ("ctf writeups", WHITE, 0),
        ("  ·  ", GREY, 0), ("Synthetix", WHITE, 0)]))
    body.append(line(Y0 + 5 * LH, 2.15, [
        ("[+] ", GREEN, 0), ("access granted", GREEN, 700)]))

    # resolved name + blinking block cursor (tspan auto-positions, no width math)
    name_y = H - 54
    name = (
        f'<g opacity="0">'
        f'<animate attributeName="opacity" values="0;1" dur="0.5s" begin="2.7s" fill="freeze"/>'
        # blurred glow copy behind
        f'<text x="{X}" y="{name_y}" font-size="40" font-weight="700" '
        f'fill="{GREEN}" filter="url(#glow)" font-family="{MONO}">Sarvesh M</text>'
        # sharp text on top, cursor rides along as a tspan (fill-opacity blinks)
        f'<text x="{X}" y="{name_y}" font-size="40" font-weight="700" fill="{GREEN}" font-family="{MONO}">'
        f'Sarvesh M<tspan fill="{GREEN}"> █'
        f'<animate attributeName="fill-opacity" values="1;1;0;0" keyTimes="0;0.49;0.5;1" '
        f'dur="1.05s" begin="3s" repeatCount="indefinite"/></tspan></text>'
        # tagline, right-aligned so it never collides with the name
        f'<text x="{W-28}" y="{name_y}" text-anchor="end" font-size="15" '
        f'font-weight="500" fill="{GREY}" font-family="{MONO}">//KuantumKnight · builds + breaks</text>'
        f'</g>'
    )

    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}" role="img" aria-label="terminal hero: Sarvesh M, builds things then breaks them">
  <defs>
    <filter id="glow" x="-30%" y="-30%" width="160%" height="160%">
      <feGaussianBlur stdDeviation="6" result="b"/>
      <feComponentTransfer in="b" result="b2"><feFuncA type="linear" slope="0.5"/></feComponentTransfer>
      <feMerge><feMergeNode in="b2"/></feMerge>
    </filter>
    <pattern id="scan" width="3" height="4" patternUnits="userSpaceOnUse">
      <rect width="3" height="1" y="0" fill="{GREEN}" opacity="0.04"/>
    </pattern>
    <linearGradient id="beamg" x1="0" x2="1" y1="0" y2="0">
      <stop offset="0" stop-color="{GREEN}" stop-opacity="0"/>
      <stop offset="0.5" stop-color="{GREEN}" stop-opacity="0.9"/>
      <stop offset="1" stop-color="{GREEN}" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="vign" x1="0" x2="0" y1="0" y2="1">
      <stop offset="0" stop-color="{GREEN}" stop-opacity="0.05"/>
      <stop offset="1" stop-color="{BG}" stop-opacity="0"/>
    </linearGradient>
  </defs>

  <!-- panel -->
  <rect x="1" y="1" width="{W-2}" height="{H-2}" rx="12" fill="{BG}" stroke="{BORDER}" stroke-width="1.5"/>
  <rect x="1" y="1" width="{W-2}" height="120" rx="12" fill="url(#vign)"/>

  <!-- title bar -->
  <rect x="1" y="1" width="{W-2}" height="40" rx="12" fill="{PANEL}"/>
  <rect x="1" y="28" width="{W-2}" height="13" fill="{PANEL}"/>
  <line x1="1" y1="41" x2="{W-1}" y2="41" stroke="{BORDER}" stroke-width="1.5"/>
  <circle cx="24" cy="21" r="6" fill="{RED}" opacity="0.85"/>
  <circle cx="44" cy="21" r="6" fill="{AMBER}" opacity="0.85"/>
  <circle cx="64" cy="21" r="6" fill="{LIME}" opacity="0.85"/>
  <text x="{W//2}" y="26" text-anchor="middle" font-family="{MONO}" font-size="13" fill="{GREY}">knight@kali: ~/profile — zsh</text>

  <!-- scanlines -->
  <rect x="2" y="42" width="{W-4}" height="{H-44}" fill="url(#scan)"/>

  <!-- one-shot scan beam during boot -->
  <g opacity="0">
    <animateTransform attributeName="transform" type="translate" values="-80 0;{W} 0" dur="2.4s" begin="0.1s" fill="freeze"/>
    <animate attributeName="opacity" values="0;0.55;0.55;0" keyTimes="0;0.08;0.85;1" dur="2.4s" begin="0.1s" fill="freeze"/>
    <rect x="0" y="42" width="60" height="{H-44}" fill="url(#beamg)"/>
  </g>

  <!-- body -->
  {''.join(body)}
  {name}
</svg>
'''
    write_svg("assets/hero.svg", svg)


if __name__ == "__main__":
    build()
